USE [master]
GO

/****** Object:  Database [SuperMarket]    Script Date: 27/05/2022 5:47:22 PM ******/
CREATE DATABASE [SuperMarket]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SuperMarket', FILENAME = N'C:\MSSQL15.MSSQLSERVER1\MSSQL\DATA\SuperMarket.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SuperMarket_log', FILENAME = N'C:\MSSQL15.MSSQLSERVER1\MSSQL\DATA\SuperMarket_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SuperMarket].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SuperMarket] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SuperMarket] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SuperMarket] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SuperMarket] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SuperMarket] SET ARITHABORT OFF 
GO

ALTER DATABASE [SuperMarket] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SuperMarket] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SuperMarket] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SuperMarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SuperMarket] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SuperMarket] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SuperMarket] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SuperMarket] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SuperMarket] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SuperMarket] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SuperMarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SuperMarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SuperMarket] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SuperMarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SuperMarket] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SuperMarket] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SuperMarket] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SuperMarket] SET RECOVERY FULL 
GO

ALTER DATABASE [SuperMarket] SET  MULTI_USER 
GO

ALTER DATABASE [SuperMarket] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SuperMarket] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SuperMarket] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SuperMarket] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SuperMarket] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SuperMarket] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SuperMarket] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SuperMarket] SET  READ_WRITE 
GO

